unreachable: unreachable.c GraphAM.c
	gcc -Wall -O3 -o unreachable unreachable.c GraphAM.c

eulerianCycle: eulerianCycle.C GraphAM.c Quack.c
	gcc -Wall -O3 -o eulerianCycle eulerianCycle.c GraphAM.c Quack.c
