prefixes: prefixes.c
	dcc -Wall -O3 -o prefixes prefixes.c

base: base.c quack.c
	dcc -Wall -O3 -o base base.c quack.c

base2: base2.c quack.c
	dcc -Wall -O3 -o base2 base2.c quack.c

structs: structs.c
	dcc -Wall -O3 -o structs structs.c

1: pointers.c
	dcc -Wall -O3 -o pointers pointers.c
