cHeap: cHeap.c
	gcc -Wall -std=c99 -O3 -o cHeap cHeap.c
args2heap: args2heap.c
	gcc -Wall -std=c99 -O3 -o args2heap args2heap.c
array2heap: array2heap.c
	gcc -Wall -std=c99 -O3 -o array2heap array2heap.c
ackermann: ackermann.c
	gcc -Wall -O3 -o ackermann ackermann.c
