recount: recount.C
	gcc -Wall -o recount recount.c
	
recount+: recount+.C
	gcc -Wall -o recount+ recount+.c

count+: count+.C
	gcc -Wall -o count+ count+.c

sumNum: sumNum.C
	gcc -Wall -o sumNum sumNum.c