testGraphAL: testGraph.c GraphAL.c
	gcc -O3 -o testGraphAL testGraph.c GraphAL.c
testGraph: testGraph.c GraphAM.c
	gcc -O3 -o testGraph testGraph.c GraphAM.c
testLL: testLL.c LL.c
	gcc -O3 -o testLL testLL.c  LL.c
